apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  namespace: bookinfo
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: details
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
    labels:
      app: details
      istio.io/rev: default
      security.istio.io/tlsMode: istio
      service.istio.io/canonical-name: details
      service.istio.io/canonical-revision: v1
      version: v1
    spec:
      containers:
        - image: docker.io/istio/examples-bookinfo-details-v1:1.15.0
          imagePullPolicy: IfNotPresent
          name: details
          ports:
          - containerPort: 9080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: bookinfo-details-token-q46wl
            readOnly: true
        - args:
          - proxy
          - sidecar
          - --domain
          - $(POD_NAMESPACE).svc.cluster.local
          - --serviceCluster
          - details.$(POD_NAMESPACE)
          - --proxyLogLevel=warning
          - --proxyComponentLogLevel=misc:error
          - --trust-domain=cluster.local
          - --concurrency
          - "2"
          env:
          - name: JWT_POLICY
            value: first-party-jwt
          - name: PILOT_CERT_PROVIDER
            value: istiod
          - name: CA_ADDR
            value: istiod.istio-system.svc:15012
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.serviceAccountName
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: CANONICAL_SERVICE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels['service.istio.io/canonical-name']
          - name: CANONICAL_REVISION
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels['service.istio.io/canonical-revision']
          - name: PROXY_CONFIG
            value: |
              {"proxyMetadata":{"DNS_AGENT":""}}
          - name: ISTIO_META_POD_PORTS
            value: |-
              [
                  {"containerPort":9080,"protocol":"TCP"}
              ]
          - name: ISTIO_META_APP_CONTAINERS
            value: |-
              [
                  details
              ]
          - name: ISTIO_META_CLUSTER_ID
            value: Kubernetes
          - name: ISTIO_META_INTERCEPTION_MODE
            value: REDIRECT
          - name: ISTIO_METAJSON_ANNOTATIONS
            value: |
              {"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"details\",\"version\":\"v1\"},\"name\":\"details-secondary\",\"namespace\":\"bookinfo\"},\"spec\":{\"containers\":[{\"image\":\"docker.io/istio/examples-bookinfo-details-v1:1.15.0\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"details\",\"ports\":[{\"containerPort\":9080}]}],\"restartPolicy\":\"Never\",\"serviceAccountName\":\"bookinfo-details\"}}\n"}
          - name: ISTIO_META_WORKLOAD_NAME
            value: details-secondary
          - name: ISTIO_META_OWNER
            value: kubernetes://apis/v1/namespaces/bookinfo/pods/details-secondary
          - name: ISTIO_META_MESH_ID
            value: cluster.local
          - name: DNS_AGENT
          - name: ISTIO_KUBE_APP_PROBERS
            value: '{}'
          image: docker.io/istio/proxyv2:1.6.2
          imagePullPolicy: Always
          name: istio-proxy
          ports:
          - containerPort: 15090
            name: http-envoy-prom
            protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1337
            runAsNonRoot: true
            runAsUser: 1337
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/run/secrets/istio
            name: istiod-ca-cert
          - mountPath: /var/lib/istio/data
            name: istio-data
          - mountPath: /etc/istio/proxy
            name: istio-envoy
          - mountPath: /etc/istio/pod
            name: istio-podinfo
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: bookinfo-details-token-q46wl
            readOnly: true
        